# getting base image ubuntu
# FROM ubuntu
# FROM nvidia/cuda:11.1-devel-ubuntu20.04
FROM tensorflow/tensorflow:latest-gpu
# FROM nvidia/cuda:11.2.1-devel-ubuntu16.04
# FROM tensorflow/tensorflow:latest-gpu-jupyter

RUN apt-get update && apt-get install git -y && apt-get install vim -y && apt-get install wget 

RUN git clone --single-branch --branch peter-dev https://github.com/UCBerkeleySETI/BL-Reservoir.git 
# RUN apt install python3.10-pip -y  
RUN apt install python3-pip -y
RUN cd BL-Reservoir  && cd temp_meerKAT_analysis && pip3 install -r requirements.txt 
