# getting base image ubuntu
# FROM ubuntu
FROM nvidia/cuda:11.1.0-devel-ubuntu18.04

RUN apt-get update && apt-get install git -y && apt-get install vim -y && apt-get install wget 
RUN git clone --single-branch --branch peter-dev https://github.com/UCBerkeleySETI/BL-Reservoir.git 
RUN apt install python3-pip -y  
RUN cd BL-Reservoir  && cd temp_meerKAT_analysis && pip3 install -r requirements.txt 
