name: Build Docker

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
  pull_request:
    branches-ignore: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Build and push Energy Detection Image to Google Container Registry
      uses: docker/build-push-action@v1
      with:
          username: _json_key
          password: ${{ secrets.GCP_JSON_KEY }}
          registry: gcr.io
          repository: breakthrough-listen-sandbox/bl-scale
          dockerfile: energy-detection.dockerfile
          tags: energy-detection-latest

    # Runs a single command using the runners shell
    - name: Build and push Energy Detection Image to dockerhub
      uses: docker/build-push-action@v1
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: fx196/bl-scale
          dockerfile: energy-detection.dockerfile
          tags: energy-detection-latest
