# This is a basic workflow to help you get started with Actions

name: singularity

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ peterma-dev ]
  pull_request:
    branches: [ peterma-dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup - gcloud / gsutil
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_JSON_KEY }}
          project_id: breakthrough-listen-sandbox/bl-scale
          export_default_credentials: true

      # Runs a single command using the runners shell
      - name: checkout
        run: ls

      - name: cd into dir and build
        run: cd temp_meerKAT_analysis & ls & sudo docker build -t peterma-dev_remote temp_meerKAT_analysis/.

        
      - name: save image
        run: sudo docker save -o peterma-dev_remote.tar peterma-dev_remote
        
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo done
