name: Update Tag
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          custom_tag: dev
          dry_run: true
          github_token: ${{ secrets.ACCESS_TOKEN }}
